### PR TITLE
Fix language service crash after viewing opened feature file diff in Visual Studio

### PR DESCRIPTION
**Pull request by rik-smeets**
Resolves https://github.com/techtalk/SpecFlow/issues/863

### CODE REVIEW

**Comment by SabotageAndi** [comment]
Thanks for having a look at this issue.
Are you finished with this PR? Can I merge it?

**Comment by rik-smeets** [comment]
I'm finished with this PR, so you can merge it if you like. Maybe you'd like to test it beforehand, but I'll leave that up to you! I did test it myself of course by the way :-).

**Comment by SabotageAndi** [comment]
Cool! After the merge it a release will pushed to our VSIX Galery on MyGet. @david1995 and I are working with the latest version from there the whole time. When everything works for some days, we will upload it to the marketplace.

**Comment by SabotageAndi** [comment]
Thanks for your contribution to SpecFlow. If you would like us to send you some SpecFlow stickers as a thank you, please fill out the form [here](https://specflow.org/contributer-package/).

**Comment by SabotageAndi** [comment]
Resolves https://github.com/techtalk/SpecFlow/issues/1396

**Pull request merged**
