### PR TITLE
Upgraded Extension for VS2017

### PR DESCRIPTION
**Pull request by paulroho**
Did this mainly by following the instructions in https://github.com/Microsoft/visualstudio-docs/blob/master/docs/extensibility/how-to-migrate-extensibility-projects-to-visual-studio-2017.md

### CODE REVIEW

**Comment by SabotageAndi** [comment]
Thanks @paulroho for the PR.
As we have different branches for the different Visual Studio versions, I created a VS2017 branch. Could you change the PR to this branch?
Thanks!

**Comment by robbell** [comment]
Has this been released yet?

**Comment by SabotageAndi** [comment]
Yes. See https://github.com/techtalk/SpecFlow/issues/744
VS Marketplace: https://marketplace.visualstudio.com/items?itemName=TechTalkSpecFlowTeam.SpecFlowforVisualStudio2017

**Comment by robbell** [comment]
Thanks. It looks as though .NET Core support is still coming though - is that right? I've seen SpecFlow.NetCore, but that seems to be aimed at the problems arising from .xproj, but doesn't seem to work since the reversion to XML-based .csproj files.

**Comment by SabotageAndi** [comment]
PR for .NET Core is here: https://github.com/techtalk/SpecFlow/pull/649
But it will take a while until it is completed.
SpecFlow.NetCore is not from us. Please ask the maintainer of it.

**Pull request merged**
