### PR TITLE
#481: Add scrollbars to intelliSense

### PR DESCRIPTION
**Pull request by Dreamescaper**
IntelliSense popup is now scrollable.
scrollbars

### CODE REVIEW

**Comment by SabotageAndi** [comment]
The build error is for VS2017. This is probably to some changes in VS2017. I will have a look at it.

**Comment by Dreamescaper** [comment]
@SabotageAndi  VS2015 solution seems to be broken as well. It build successfully (under VS2013), but generated VSIX is not installable for VS2015.

**Comment by SabotageAndi** [comment]
@Dreamescaper You can not install the VS2013 VSIX into VS2015. For that you have to build the SpecFlow.VisualStudio.2015.sln in VS2015.
The master-branch is now able to build the extension for all Visual Studio versions and so the VS2015-branch is deprecated since December.

**Comment by SabotageAndi** [comment]
@Dreamescaper VS2017 build is now fixed. Please rebase your PR.

**Comment by Dreamescaper** [comment]
@SabotageAndi Done.

**Pull request merged**
