### PR TITLE
Support IDE Binding class inheritance and Visual Studio csproj backward compatiblilty

### PR DESCRIPTION
**Pull request by kdfrie**
I found that when I had a base class without a Binding attribute and a subclass with a binding attribute, the IDE did not find the bindings in the base class. The specflow engine works fine with this configuration - it is simply the ide that has issues.  Adding a binding attribute to the base class results in duplicate bindings by the engine as well as duplicate instantiations which is problematic when using the dependency injection mode.  

This code fixes this by chaining into the base classes when looking for bindings.  I have not implemented change tracking on the base class, so you have to dirty the class with the binding attribute to get updates.

I had some struggles getting this working targetting VS 2012.  I updated the csproj to be compatible with VS 2012 and VS 2013 per the following:

http://blogs.clariusconsulting.net/kzu/how-to-create-a-visual-studio-extensibility-project-that-is-compatible-with-vs-2010-2012-and-2013/

### CODE REVIEW

**Comment by gasparnagy** [comment]
Thx. Have you compiled/tested this on VS2012? Because I see some strange changes in the project file and in the manifest.

**Comment by kdfrie** [comment]
Hi Gáspár,

Yes, I have been using this extensively in VS2012 and have used VS2012 to
compile it.  That is the purpose of all these strange changes - so that one
version of the csproj can be used with mutliple versions of visual studio.
Supposedly, VS2010 should work too, but I don't have VS2010 to test with.

Thank you for your great work on this project!

**Comment by gasparnagy** [comment]
This is a great improvement, but our strategy is not to mix target VS versions within the same code base (we tried, but in long term it causes quite a pain). This branch is for VS2013. We did not plan to make an upgrade for VS2012 (we can make it still), but that would be in another branch then.

Would you be interested to redo this PR for VS2013? You can install VS2103 Community edition (for working on SpecFlow, it is free). Once we have this for VS2013, we can still consider to downgrade the source code to VS2012 on another branch.

**Comment by kdfrie** [comment]
I can make a another pull request quite easily as I separated the two
changes in separate commits.

I can understand the pain of multiple VS targets as that is what I
struggled with in regards to the csproj changes.  Fortunately, the code
itself is happy with VS2012 and VS2013 and the pain is all in selecting the
correct assembly references.  That being said, I was considering making
change tracking work on base classes when they are located in independent
files.  It would be easy in VS2013 because EnvDTE supports listing of all
subclasses,  This is not implemented in 2012 and would be more work.

I did download VS2013 CE, compile and run some cursory tests against it as
well.  It seems like it would be a good thing to have the option of
compiling with 2012 even if the strategy is to target and release new
versions for 2013 only.

**Pull request closed without merging**
