### PR TITLE
Add columns names to autocomplete suggestions

### PR DESCRIPTION
**Pull request by slig3**
1. When displaying auto-complete suggestions, also display the column names beside it in parenthesis. 
autocompletefix

2. In CompletionCommandFilter.cs : Fix bug where trying to show autocomplete suggestions on a scenario name would give an error message ("The operation could not be completed") instead of just displaying nothing.

### CODE REVIEW

**Comment by SabotageAndi** [comment]
Nice! Thanks for the PR.
I am not sure if I find time this week to review it. But next week for sure.

**Comment by slig3** [comment]
Hi @SabotageAndi , did you have time to look at this PR? 
Also, I was wondering if there is a date scheduled for the next release of this project?

**Comment by SabotageAndi** [comment]
Sorry, not yet. Too much other work to do.

The next release to the marketplace will be when https://github.com/techtalk/SpecFlow/issues/1311 is fixed.
You can get earlier binaries from this VSGallery feed: https://www.myget.org/F/specflow-vsix/vsix/

**Comment by slig3** [comment]
Hi @SabotageAndi , just making sure this PR hasn't been forgotten. :)

**Comment by slig3** [comment]
Hi, did someone had time to look at this PR? Thanks!

**Comment by slig3** [comment]
Created new PR https://github.com/techtalk/SpecFlow.VisualStudio/pull/56 because this one was open for too long and had too much conflicts.

**Pull request closed without merging**
