### PR TITLE
Fix for right-click context with Resharper 2017.1

### PR DESCRIPTION
**Pull request by JMontagu**
Adds right-click context support for Resharper 2017.1 (v108); the alias for 'ReSharper_UnitTest**Run**Context' [was changed](https://www.jetbrains.com/help/resharper/2017.1/Reference__Keyboard_Shortcuts.html) to 'ReSharper_UnitTest**RunFrom**Context'.

Currently running SpecFlow via right-click context with ReSharper 2017.1 will throw the exception 
```ReSharper6TestRunnerGateway: test tool error: System.Runtime.InteropServices.COMException (0x80004005): Command "ReSharper.ReSharper_UnitTestRunContext" is not valid.```
And display the modal error 'Object reference not set to an instance of an object.'

### CODE REVIEW

**Comment by JMontagu** [comment]
Build failing; looks to be an issue with AppVeyor build image?

**Comment by SabotageAndi** [comment]
Yes, looks like AppVeyor changed their images.
I will have a look at it in the next days.

**Comment by SabotageAndi** [comment]
@JMontagu AppVeyor build should work now

**Comment by JMontagu** [comment]
@SabotageAndi thanks, build passing now 😄

**Pull request merged**
