### PR TITLE
Add FormatDocument command for feature files

### PR DESCRIPTION
**Pull request by littlegenius666**
Original PR from @Dreamescaper and @claudiobernasconi

Features added:
- choose what will be used for an indent (tabs or spaces)
- choose if lines will be normalized or not
- fixed "jumping cursor" issue
- fixed formatting crashing when the table has only headers
- select the size of indent for different sections of the feature file

### CODE REVIEW

**Comment by littlegenius666** [comment]
@SabotageAndi @Dreamescaper @claudiobernasconi Please advise if you have any additional thoughts on this

**Comment by SabotageAndi** [comment]
I will have a look at it in the next days. New sprint starts tomorrow and I will add it to it.

**Comment by littlegenius666** [comment]
> I will have a look at it in the next days. New sprint starts tomorrow and I will add it to it.

Thanks!

**Comment by SabotageAndi** [comment]
I tried it out and it worked really well!
Thanks @littlegenius666, @claudiobernasconi and @Dreamescaper for this new feature. You will make a lot of SpecFlow users happy.

If you would like us to send you some SpecFlow stickers as a thank you, please fill out the form [here](https://specflow.org/contributer-package/).

**Pull request merged**
