### PR TITLE
Loading generator assembly without changing ApplicationBase folder

### PR DESCRIPTION
**Pull request by SabotageAndi**
to fix https://github.com/techtalk/SpecFlow/issues/857

### CODE REVIEW

**Comment by SabotageAndi** [comment]
@gasparnagy Could you have a look at this?
It could fix https://github.com/techtalk/SpecFlow/issues/857, as with this change, we don't change the ApplicationBase Path for the new appdomain any more. So the original path and original binding redirects should be used.

**Comment by bcexopolllo** [comment]
@SabotageAndi Hello,
After hours of struggling (resolving dependencies and manifest version handling) were built 
[TechTalk.SpecFlow.VsIntegration.2017.zip](https://github.com/techtalk/SpecFlow.VisualStudio/files/1603916/TechTalk.SpecFlow.VsIntegration.2017.zip)

tested it on different specflow versions result is next:
first time when you open VS it's usually OK, and tool successfully generates sub-feature classes,
but right after solution was rebuilt - i receives next errors:

> #error Generation error: Loading this assembly would produce a different grant set from other instances. (Exception from HRESULT: 0x80131401)

were fixed after deleting outdated extension at C:\Users\[user]\AppData\Local\Microsoft\VisualStudio\15.0_0dc156ad\Extensions\2kdnctyd.ho2

> #error TechTalk.SpecFlow.Generator.Interfaces.TestGenerationError

> Custom tool error: Generation error: Method 'RegisterDependencies' in type 'TechTalk.SpecRun.SpecFlowPlugin.Generator.SpecFlowGeneratorPlugin' from assembly 'SpecRun.SpecFlowPlugin, Version=1.5.2.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

> Custom tool error: Generation error: Could not load file or assembly 'TechTalk.SpecFlow, Version=2.1.0.0, Culture=neutral, PublicKeyToken=0778194805d6db41' or one of its dependencies. The system cannot find the file specified.	Deloitte.IMOS.UI.FunctionalTests


and if again close/open VS and regenerate feature files -- files will be generated successfully without any errors until you rebuild the project and tried to regenerate them again...

**Comment by SabotageAndi** [comment]
Thanks for the info. I will try it with rebuilding the projects.
I only tested it without it.

**Comment by rocknet** [comment]
If this gets packaged into a VSIX maybe in myget or something I'd be happy to help test.

**Comment by SabotageAndi** [comment]
@bcexopolllo  I wasn't able to reproduce your error when rebuilding a project. I used this solution for testing: https://github.com/SabotageAndi/SpecFlow.Example.AllTestRunners
Could you try if you get the error with this? Perhaps there is something special in your project, that isn't in my test project.

@rocknet You can find the artifacts/VSIX in the AppVeyor build: https://ci.appveyor.com/project/SpecFlow/specflow-visualstudio/build/2017.1.11-PullRequest.26+4.build.128

**Comment by bcexopolllo** [comment]
@SabotageAndi Yes, me too wasn't able to reproduce the issue on your project even with all references installed that we have. Everything works perfect and fast.
My assumptions are only related to complex dependecies between projects inside the solution that contains proxies/wrappers of webdrivers, pagefactory, and different reporttools that also using SpecFlow as testrunner

But what I've noticed - I received new error in our solution after I downloaded and work on your project. Here it is:

> Custom tool error: Generation error: Missing [assembly:GeneratorPlugin] attribute in C:\Users\user\AppData\Local\Microsoft\VisualStudio\15.0_0dc156ad\Extensions\2kdnctyd.ho2\SpecRun.SpecFlowPlugin.dll	

And also what I've noticed - in logs (Specflow output) in your project I've received that kind of warning message:

> [12:06:15.4927098] ProjectFeatureFilesTracker: Cannot detect generated test version for file: XUnit2.SpecFlowFeature1.feature, error: Method 'RegisterDependencies' in type 'TechTalk.SpecRun.SpecFlowPlugin.Generator.SpecFlowGeneratorPlugin' from assembly 'SpecRun.SpecFlowPlugin, Version=1.5.2.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

that very similar to what we have previously:

> Custom tool error: Generation error: Could not load file or assembly 'TechTalk.SpecFlow, Version=2.1.0.0, Culture=neutral, PublicKeyToken=0778194805d6db41' or one of its dependencies. The system cannot find the file specified.	Deloitte.IMOS.UI.FunctionalTests

Please checkout my branch:
https://github.com/bcexopolllo/SpecFlow.VisualStudio/tree/SpecflowIssueDetection

**Comment by fredrikeriksson** [comment]
This change also fixed the  `#error Generation error: Could not load file or assembly 'Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.` exception for me.
For reference I was using Visual Studio 2017 Enterprise 15.5.3 with SpecFlow 2.2.1 and MSTest2 1,2,0.

We're gonna start using this in a project and this was blocking me (kind of lucky that i began with this today) so I haven't tested it beyond getting it to work. :)

**Comment by SabotageAndi** [comment]
@DanielTheCoder please verify if it fixes the issue for you in your environment

**Comment by fredrikeriksson** [comment]
After I've been dabbling a while now I also experience the mentioned `Loading this assembly would produce a different grant set from other instances.` exception... 

Don't know if this will be of any help: [https://support.microsoft.com/sv-se/help/2282372/-loading-this-assembly-would-produce-a-different-grant-set-from-other](url)

**Comment by rocknet** [comment]
@SabotageAndi In VS 15.5.2, I removed 2017.1.10, and installed the VSIX from the build.  I don't get the Microsoft.Build.Framework error I did in https://github.com/techtalk/SpecFlow/issues/857, but now the generated code behind has only this in the output:
#error Generation error: Loading this assembly would produce a different grant set from other instances. (Exception from HRESULT: 0x80131401)

**Comment by DanielTheCoder** [comment]
@SabotageAndi: the problem is not solved, now we have the same issue @fredrikeriksson described.
#error Generation error: Loading this assembly would produce a different grant set from other instances. (Exception from HRESULT: 0x80131401)
Before trying out this version I've reinstalled the current version from gallery with no change.

**Comment by SabotageAndi** [comment]
@DanielTheCoder I changed the code so, that if it wants to resolve an already loaded assembly, it is not loading the assembly again.
The error message could be came from, when you are loading the same assembly with different permissions in the same appdomain again (https://stackoverflow.com/a/17496937/3155323).
Could you try it again?

**Comment by DanielTheCoder** [comment]
@SabotageAndi: I'll try to test it today,
can you additionally add a unique identifier for the used app domains and add it to the log output?
Maybe we've a race condition where we are using the wrong app domain for the generator?

**Comment by fredrikeriksson** [comment]
@SabotageAndi this build fixed the last issue for me. :+1: 
On a side note, before this build I downgraded to 1.9.0 because I noticed that specific version number being written in the generated files comments and that made it work again. 
Might've been something with my environment but I thought it would be worth mentioning at least :)

**Comment by SabotageAndi** [comment]
@fredrikeriksson You mean the "Loading this assembly would produce a different grant set from other instances." exception?

**Comment by fredrikeriksson** [comment]
@SabotageAndi Yes exactly, I've been working for a couple of hours now with it and haven't experienced any issues what so ever.

**Comment by PhilipGullick** [comment]
I also applied this fix; it fixed the generation error - however it seems to be compiling with 1.9.0 generators again instead of 2.2.0:

// <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>

This may just be the old issue from #991 though?

**Comment by SabotageAndi** [comment]
Aaarg, ... I hoped https://github.com/techtalk/SpecFlow/issues/991 will be also fixed with this ... :-(

**Comment by PhilipGullick** [comment]
I have unloaded wix projects, cleared temp etc.

I haven't done a clean install of SpecFlow yet though, I can try that first and let you know the result.

**Comment by rocknet** [comment]
VS 15.5.2, Specflow 2.1.0.  VSIX from : https://ci.appveyor.com/project/SpecFlow/specflow-visualstudio/build/2017.1.11-PullRequest.26+6.build.129/job/dsxjn0j40bhq7i2l/artifacts

I still get #error Generation error: Loading this assembly would produce a different grant set from other instances. (Exception from HRESULT: 0x80131401)

Let me know if there's anything I can provide to help.

**Comment by fredrikeriksson** [comment]
I began to experience `Loading this assembly would produce a different grant set from other instances. (Exception from HRESULT: 0x80131401)` again after I started to dabble with custom generator plugins :/
Seems to me that this exception also gets thrown when loading them, it works fine the first time it loads the assembly, which is the same behaviour as we experienced in the first occurance.

**Comment by PhilipGullick** [comment]
`

I have unloaded wix projects, cleared temp etc.I haven't done a clean install of SpecFlow yet though, I can try that first and let you know the result.
--


` 

To no avail, still generating with 1.9.0.
So for me, the exception has now gone, however the 1.9.0 generator issue has re-surfaced (my previous work around was to unload Wix projects within the solution, this no longer works for me as a work around).

**Comment by fredrikeriksson** [comment]
@SabotageAndi Besides the previous mentioned exception I'm also experiencing issues with locking of plugin assemblies. It works fine the first time the plugin project is build and copied over but after the Generator has been used once it gets locket and I have to restart VS to release the lock.
I suspect that the usage of `Assembly.LoadFile` is creating this issues. As far as I've read `Assembly.Load(System.IO.File.ReadAllBytes(path)) should be a better choice. 
Of course I don't know the whole picture so it might not work in this context.

Unsure if the locks and `Loading this assembly would produce a different grant set from other instances.` is connected in any way,

Both of these issues can be worked around by restarting VS, so it's not a complete showstopper.
But it's annoying none the less to be forced to restart so many times while developing the Plugin.

Also, the change that prevents repeated loads of assemblies, does that apply on CustomPlugins too?

**Comment by SabotageAndi** [comment]
@fredrikeriksson 
Ok, assembly locking is not good. Perhaps the AppDomain of the generator is not unloaded because of something ... No idea why.. :-(

The change for preventing repeated loads should also apply to custom generator plugins, as the AssemblyResolve event handler is removed after the generation of the code behind file.

Question for you: If you are using CustomPlugins, why don't you use the MSBuild integration? You are a SpecFlow "poweruser", when you use your own plugins. ;-)

**Comment by fredrikeriksson** [comment]
@SabotageAndi Thanks for the pointers, I must admit though that I'm quite new with SpecFlow so I'm still in the learning phase :)

**Comment by SabotageAndi** [comment]
The reason for the "Loading this assembly would produce a different grant set from other instances." exception is an old version of the Gherkin parser. See #1015 for details.

**Comment by kooolandy** [comment]
Hi I have just setup a new pc with VS2017 version 15.5.5 with extension 2017.1.10 and project has been upgraded to Specflow 2.2.0.0.  The manual regeneration from solution explorer IRegenerate Feature files menu item) fails but the auto-regeneration (when I change app.config) works.

Hope this helps anyone!

**Pull request merged**
